- name: ping the server # Play name
  hosts: ansible      # Inventory group to target
  tasks:
  - name: ping the web server  # Task name
    ansible.builtin.ping:      # Module it runs the ping module and checks SSH connectivity, Python availability, authentication
                               # If successful, youâ€™ll see: SUCCESS => {"ping": "pong"}
  